### ISSUE TITLE
Save audio offline first and upload after on Firestore

### ISSUE THREAD

**Issue by nidelson** [monkick/recording-button#2]
Hello! 
Congratulations on the component!
I need support:
My system works offline. I need to record the audio, attach it to a document and send it online.
Tried trying to use `recordingSoundUrl`. Any suggestion?
Thank you!

**Comment by kazu80** [comment]
Hi @nidelson. Thank you for use it! 
`recordingSoundUrl` is the URL of the recorded sound for download.
If haven't it. It will be null. 
If updated it. It will be updated.

So you can use it.
Is the answer right? I'm not good at English.

**Comment by nidelson** [comment]
Yes! Thanks!
